### ISSUE TITLE
Chaining .count with join results in invalid mysql statement

### ISSUE THREAD

**Issue by adamonduty** [aub/record_filter#3]
First of all, I have to congratulate you for excellent work on record_filter! I was having problems with named_scope, joins and table aliasing that your plugin handled effortlessly.

I noticed a small bug in the SQL generated when using a join. I'm writing a query named_filter on my model that looks like this:

named_filter(:query) do |q|
  with(:comments).like("%#{q}%")
  having(:user).having(:posts).with(:title).like("%#{q}%")
end

Model.query('a') produces correct results, but Model.query('a').count creates an invalid mysql statement. I found that it is an easy fix. The first query generates 

SELECT count(*) as count_all FROM ... 

while the second generates 

SELECT count(`model`.*) as count_model_all FROM ...

Mysql requires either "*" or the name of a specific field (such as `model`.`id`).

**Comment by aub** [comment]
Hi adamonduty,

Sorry I didn't see this earlier. I'm pretty sure I didn't get an email when you posted it and haven't checked the issues in a while. In any case, I'm not able to reproduce this. If you still can, can you fork the gem and write me a spec that does and I'll write the code to fix it? Thanks.

**Comment by adamonduty** [comment]
Aub,

It seems that in my lateness I also cannot reproduce the problem. Looking through record_filter it doesn't appear that you use anything but the AR method count (and don't build count queries manually). My best guess is that I had an old version of will_paginate or something else that was choking on the join condition, and I mistakenly took the problem to be associated with record_filter.

If I can ever reproduce the problem I'll send a spec your way.

**Comment by aub** [comment]
Seems that this is no longer an issue
