### ISSUE TITLE
Allow access to association extensions through filters

### ISSUE THREAD

**Issue by oggy** [aub/record_filter#8]
It would be nice to be able to do this, to mirror named_scope:

```
Blog.named_filter(:published) { ... }
Blog.has_many :posts, :extend => Module.new{def foo ... end}
blog.posts.published.foo
```

**Comment by aub** [comment]
Haha, what the heck?

**Comment by oggy** [comment]
Sorry, just cleaning up my /issues page in an attempt to make it useful. :)

I do miss this library. Much better DSL than ActiveRecord!
